import type { Metadata } from "next";
import "./globals.css";
import MultiProvider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MultiProvider>
        <body>{children}</body>
      </MultiProvider>
    </html>
  );
}
